spring.application.name=fraudchecker

# Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_db
spring.datasource.username=vince_admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (Gestão de Migrations)
spring.flyway.enabled=true
